name: Update package.json

on: workflow_dispatch

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install jq

    - name: Update package.json
      run: |
        jq --arg linuxArtifactName 'hallo-install-${arch}.${ext}' \
           --arg winMacArtifactName 'hallo-install.${ext}' \
        '.name="hallo" |
            .productName="HALLO Desktop" |
            .description="App für HALLO - vom Ev. Johanneswerk" |
            .build.productName="HALLO Desktop" |
            .build.mac.artifactName=$winMacArtifactName |
            .build.mac.extendInfo.NSCameraUsageDescription="HALLO braucht für Videokonferenzen Zugriff auf die Kamera." |
            .build.mac.extendInfo.NSMicrophoneUsageDescription="HALLO braucht für Videokonferenzen Zugriff auf das Mikrofon." |
            .build.linux.artifactName=$linuxArtifactName |
            .build.linux.executableName="hallo-install" |
            .build.win.artifactName=$winMacArtifactName |
            .build.protocols[0].schemes[0]="hallo" |
            .repository.url="git://github.com/de-johannes/hallo-desktop"
            ' package.json > temp.json && mv temp.json package.json

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Update package.json" || echo "No changes to commit"
        git push
